encode-img:
	python steganography.py merge --img1=../imgs/imgs-cover/cover_img.png --img2=../imgs/imgs-secret/secret_img.png --output=../imgs/imgs-steg/steg_img.png
decode-img:
	python steganography.py unmerge --img=../imgs/imgs-steg/steg_img.png --output=../imgs/imgs-un/un_img.png