encode:
	python steglsb.py -e ../imgs/imgs-cover/cover_img.png ../imgs/imgs-secret/secret_img.png 3 ../imgs/imgs-steg/steg_img.png

decode:
	python steglsb.py -d ../imgs/imgs-steg/steg_img.png 3 ../imgs/imgs-un/un_img.png

display-steg:
	display ../imgs/imgs-steg/steg_img.png

display-un:
	display ../imgs/imgs-un/un_img.png